### Keycloak & Kong Integration Test Suite
### Variables
@keycloak_host = http://keycloak.192.168.100.240.nip.io
@realm = lab-realm
@kong_echo = http://192.168.100.240/echo-protected

### 1. Keycloak OIDC Discovery Endpoint (.well-known)
GET {{keycloak_host}}/realms/{{realm}}/.well-known/openid-configuration
Accept: application/json

### 2. Keycloak Public Certs (JWKS endpoint)
GET {{keycloak_host}}/realms/{{realm}}/protocol/openid-connect/certs
Accept: application/json

### 3. User Login - Resource Owner Password Grant
# @name login
POST {{keycloak_host}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=demo-app
&username=alice
&password=Password123!
&grant_type=password

### 4. Extract Token from login response
@authToken = {{login.response.body.access_token}}
@refreshToken = {{login.response.body.refresh_token}}

### 5. Call Kong Echo Service WITHOUT Token (Expect 401)
GET {{kong_echo}}

### 6. Call Kong Echo Service WITH Bearer Token (Expect 200)
GET {{kong_echo}}
Authorization: Bearer {{authToken}}

### 7. Refresh Token Flow
POST {{keycloak_host}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=demo-app
&grant_type=refresh_token
&refresh_token={{refreshToken}}

### 8. User Info Endpoint
GET {{keycloak_host}}/realms/{{realm}}/protocol/openid-connect/userinfo
Authorization: Bearer {{authToken}}
